### ISSUE TITLE
Caricamento dati da file è una sezione

### ISSUE THREAD

**Issue by Polpetta** [R-and-LaTeX/CorsoDiR#17]
Caricamento dati da file ma sarebbe meglio fosse un capitolo altrimenti rompe tutta la formattazione del documento!

**Comment by Polpetta** [comment]
Allego screenshot
![image](https://user-images.githubusercontent.com/5928183/31576116-128514ba-b0f5-11e7-800d-bfebb4c0e390.png)

**Comment by mzanella** [comment]
Sistemato in #12
