### ISSUE TITLE
Comandi base 2 - Altri comandi

### ISSUE THREAD

**Issue by Polpetta** [R-and-LaTeX/CorsoDiR#6]
Spiegare i seguenti comandi:
- [x] pulizia ambiente
- [x] dim
- [x] covarianza
- [x] varianza
- [x] moda
- [ ] devianza
- [x] deviazione standard

**Comment by mzanella** [comment]
Ho un dubbio sulla devianza:sweat_smile: non è una caratteristica di un modello?

**Comment by Polpetta** [comment]
No è dei dati
